version: '3.8'

services:
  mongodb:
    image: mongo:7.0.8
    container_name: mongo_tilted_towers
    env_file:
      - .env
    environment:
      MONGO_INITDB_DATABASE: ${DB_MONGO_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_MONGO_PASSWORD}
    ports:
      - "27018:27017"
    volumes:
      - mongodb:/data/db
    networks:
      - app_network
    restart: always

volumes:
  mongodb:

networks:
  app_network:
    name: app_network
